language: ruby
sudo: false

rvm:
  - 2.3.4

script:
  - RAIL_ENV=production rake assets

deploy:
  github_token: "$GITHUB_TOKEN"
  local_dir: public
  provider: pages
  skip_cleanup: true

env:
  global:
    secure: fXNxPUz26WJVPCPgMHps4Em8SnL6T1d67DGzluURnX9ceWoYgrLNK/gS0XQB6m/goAlFUSpFI4OghFWvwGmc66S8vrL4pUSt5iMn+3PzeYu+SvM04Kvb8VK2X+DXtys828s4vv9jf8N0EEa0QA9XdvaoJD63oMEG212L8vxFw0s=

notifications:
  email: false
